GET http://localhost:3000/plato
###
GET http://localhost:3000/tipo_plato
###

DELETE http://localhost:3000/plato/5

###
# "estado":true,
# "foto":"https://gastronomiabolivia.com/wp-content/uploads/saice-tarijeno-bolivia.jpg"
POST http://localhost:3000/plato
Content-Type: application/json

{
    "nombre":"plato 1",
    "descripcion":"descripcion 1"
}
###
POST  http://localhost:3000/servicios
Content-Type: application/json

{
    "nombre":"plato 2",
    "descripcion":"descripcion 2"
}
