POST  http://localhost:3000/reserva
Content-Type: application/json

{
    "fechareserva":"2023-11-18", 
    "fechaservicio":"2023-11-18", 
    "cupo":25, 
    "observacion":"Reserva Grande", 
    "estado":true, 
    "total":50, 
    "usuarioid":2, 
    "servicioid":8
}

###
GET http://localhost:3000/reserva
###
GET http://localhost:3000/usuario
###

DELETE http://localhost:3000/plato/5

###
# "estado":true,
# "foto":"https://gastronomiabolivia.com/wp-content/uploads/saice-tarijeno-bolivia.jpg"
POST http://localhost:3000/plato
Content-Type: application/json

{
    "nombre":"plato 1",
    "descripcion":"descripcion 1"
}
###
POST  http://localhost:3000/plato
Content-Type: application/json

{
    "nombre":"nuevo", 
    "descripcion":"descnuevo", 
    "estado":true, 
    "foto":"asda", 
    "tipoPlatoId":1
}
